// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Orgin;
RWStructuredBuffer<float3> Result;
[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float xStep= 1.0f/32.0f;
    float yStep = 1.0f/8.0f;
    //if(id.x%xStep == 0&& id.y%yStep == 0)
    {
      
        Result[id.x] = Orgin[id.xy];
    }
}
